### PR TITLE
Improved skull

### PR DESCRIPTION
**Pull request by liach**

### CODE REVIEW

**Comment by 3TUSK** [comment]
Can it be server side only...?

**Comment by liach** [comment]
> server side only

??
I still need to work on this. A bit messy and includes other changes.

**Comment by liach** [comment]
I hope to merge it soon. Too important. And I will merge it in git bash.

**Comment by 3TUSK** [comment]
_Important_?
Anyway the code looks good.

**Comment by liach** [comment]
Yes major changes are included here. Actually there's nothing in master now... I've been in China and have not coded for some weeks.

**Comment by 3TUSK** [comment]
Well done!

**Comment by liach** [comment]
So I'd sync and squash... Too many commits. Still good.

**Pull request merged**
